global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'kirk-grpc-service-monitor'

rule_files:


scrape_configs:
  - job_name: 'grpcserver'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9092']

  - job_name: 'grpcclient'
    scrape_interval: 1s
    static_configs: 
      - targets: ['localhost:9094']
