apiVersion: v1
kind: Service
metadata:
  labels:
    app: cncf-service
  name: cncf-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cncf-service
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

